/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package tablealias.dto;


import java.io.Serializable;
import java.util.Date;

public class ParamConsultaDto implements Serializable
{
	/** 
	 * This attribute maps to the column ID_CONSULTA in the PARAM_CONSULTA table.
	 */
	protected long idConsulta;

	/** 
	 * This attribute maps to the column FECHA in the PARAM_CONSULTA table.
	 */
	protected Date fecha;

	/** 
	 * This attribute maps to the column TOTAL_REGISTROS in the PARAM_CONSULTA table.
	 */
	protected long totalRegistros;

	/** 
	 * This attribute maps to the column UBICACION_GEOGRAFICA in the PARAM_CONSULTA table.
	 */
	protected String ubicacionGeografica;

	/** 
	 * This attribute maps to the column ACTIVIDAD_ECONOMICA in the PARAM_CONSULTA table.
	 */
	protected String actividadEconomica;

	/** 
	 * This attribute maps to the column ESTRATO_PERSONAL in the PARAM_CONSULTA table.
	 */
	protected String estratoPersonal;

	/** 
	 * This attribute maps to the column NOMBRE_ESTABLECIMIENTO in the PARAM_CONSULTA table.
	 */
	protected String nombreEstablecimiento;

	/** 
	 * This attribute maps to the column CALLE in the PARAM_CONSULTA table.
	 */
	protected String calle;

	/** 
	 * This attribute maps to the column COLONIA in the PARAM_CONSULTA table.
	 */
	protected String colonia;

	/** 
	 * This attribute maps to the column CODIGO_POSTAL in the PARAM_CONSULTA table.
	 */
	protected String codigoPostal;

	/** 
	 * This attribute maps to the column CORREDOR_INDUSTRIAL in the PARAM_CONSULTA table.
	 */
	protected String corredorIndustrial;

	/** 
	 * This attribute maps to the column RAZON_SOCIAL in the PARAM_CONSULTA table.
	 */
	protected String razonSocial;

        private String actividadEspecifica;
        
	/** 
	 * This attribute maps to the column FILTRO in the PARAM_CONSULTA table.
	 */
	protected String filtro;

	/**
	 * Method 'ParamConsulta'
	 * 
	 */
	public ParamConsultaDto()
	{
	}

	/**
	 * Method 'getIdConsulta'
	 * 
	 * @return long
	 */
	public long getIdConsulta()
	{
		return idConsulta;
	}

	/**
	 * Method 'setIdConsulta'
	 * 
	 * @param idConsulta
	 */
	public void setIdConsulta(long idConsulta)
	{
		this.idConsulta = idConsulta;
	}

	/**
	 * Method 'getFecha'
	 * 
	 * @return Date
	 */
	public Date getFecha()
	{
		return fecha;
	}

	/**
	 * Method 'setFecha'
	 * 
	 * @param fecha
	 */
	public void setFecha(Date fecha)
	{
		this.fecha = fecha;
	}

	/**
	 * Method 'getTotalRegistros'
	 * 
	 * @return long
	 */
	public long getTotalRegistros()
	{
		return totalRegistros;
	}

	/**
	 * Method 'setTotalRegistros'
	 * 
	 * @param totalRegistros
	 */
	public void setTotalRegistros(long totalRegistros)
	{
		this.totalRegistros = totalRegistros;
	}

	/**
	 * Method 'getUbicacionGeografica'
	 * 
	 * @return String
	 */
	public String getUbicacionGeografica()
	{
		return ubicacionGeografica == null ? "' '" : ubicacionGeografica;
	}

	/**
	 * Method 'setUbicacionGeografica'
	 * 
	 * @param ubicacionGeografica
	 */
	public void setUbicacionGeografica(String ubicacionGeografica)
	{
		this.ubicacionGeografica = ubicacionGeografica;
	}

	/**
	 * Method 'getActividadEconomica'
	 * 
	 * @return String
	 */
	public String getActividadEconomica()
	{
		return actividadEconomica == null ? "' '" : actividadEconomica;
	}

	/**
	 * Method 'setActividadEconomica'
	 * 
	 * @param actividadEconomica
	 */
	public void setActividadEconomica(String actividadEconomica)
	{
		this.actividadEconomica = actividadEconomica;
	}

	/**
	 * Method 'getEstratoPersonal'
	 * 
	 * @return String
	 */
	public String getEstratoPersonal()
	{
		return estratoPersonal  == null ? "' '" : estratoPersonal;
	}

	/**
	 * Method 'setEstratoPersonal'
	 * 
	 * @param estratoPersonal
	 */
	public void setEstratoPersonal(String estratoPersonal)
	{
		this.estratoPersonal = estratoPersonal;
	}

	/**
	 * Method 'getNombreEstablecimiento'
	 * 
	 * @return String
	 */
	public String getNombreEstablecimiento()
	{
		return nombreEstablecimiento;
	}

	/**
	 * Method 'setNombreEstablecimiento'
	 * 
	 * @param nombreEstablecimiento
	 */
	public void setNombreEstablecimiento(String nombreEstablecimiento)
	{
		this.nombreEstablecimiento = nombreEstablecimiento;
	}

	/**
	 * Method 'getCalle'
	 * 
	 * @return String
	 */
	public String getCalle()
	{
		return calle;
	}

	/**
	 * Method 'setCalle'
	 * 
	 * @param calle
	 */
	public void setCalle(String calle)
	{
		this.calle = calle;
	}

	/**
	 * Method 'getColonia'
	 * 
	 * @return String
	 */
	public String getColonia()
	{
		return colonia;
	}

	/**
	 * Method 'setColonia'
	 * 
	 * @param colonia
	 */
	public void setColonia(String colonia)
	{
		this.colonia = colonia;
	}

	/**
	 * Method 'getCodigoPostal'
	 * 
	 * @return long
	 */
	public String getCodigoPostal()
	{
		return codigoPostal;
	}

	/**
	 * Method 'setCodigoPostal'
	 * 
	 * @param codigoPostal
	 */
	public void setCodigoPostal(String codigoPostal)
	{
		this.codigoPostal = codigoPostal;
	}


	/**
	 * Method 'getCorredorIndustrial'
	 * 
	 * @return String
	 */
	public String getCorredorIndustrial()
	{
		return corredorIndustrial;
	}

	/**
	 * Method 'setCorredorIndustrial'
	 * 
	 * @param corredorIndustrial
	 */
	public void setCorredorIndustrial(String corredorIndustrial)
	{
		this.corredorIndustrial = corredorIndustrial;
	}

	/**
	 * Method 'getRazonSocial'
	 * 
	 * @return String
	 */
	public String getRazonSocial()
	{
		return razonSocial;
	}

	/**
	 * Method 'setRazonSocial'
	 * 
	 * @param razonSocial
	 */
	public void setRazonSocial(String razonSocial)
	{
		this.razonSocial = razonSocial;
	}

	/**
	 * Method 'getFiltro'
	 * 
	 * @return String
	 */
	public String getFiltro()
	{
                if (filtro!=null && filtro.length()<1) filtro = " ";
		return filtro;
	}

	/**
	 * Method 'setFiltro'
	 * 
	 * @param filtro
	 */
	public void setFiltro(String filtro)
	{
		this.filtro = filtro;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ParamConsultaDto)) {
			return false;
		}
		
		final ParamConsultaDto _cast = (ParamConsultaDto) _other;
		if (idConsulta != _cast.idConsulta) {
			return false;
		}
		
		if (fecha == null ? _cast.fecha != fecha : !fecha.equals( _cast.fecha )) {
			return false;
		}
		
		if (totalRegistros != _cast.totalRegistros) {
			return false;
		}
		
		if (ubicacionGeografica == null ? _cast.ubicacionGeografica != ubicacionGeografica : !ubicacionGeografica.equals( _cast.ubicacionGeografica )) {
			return false;
		}
		
		if (actividadEconomica == null ? _cast.actividadEconomica != actividadEconomica : !actividadEconomica.equals( _cast.actividadEconomica )) {
			return false;
		}
		
		if (estratoPersonal == null ? _cast.estratoPersonal != estratoPersonal : !estratoPersonal.equals( _cast.estratoPersonal )) {
			return false;
		}
		
		if (nombreEstablecimiento == null ? _cast.nombreEstablecimiento != nombreEstablecimiento : !nombreEstablecimiento.equals( _cast.nombreEstablecimiento )) {
			return false;
		}
		
		if (calle == null ? _cast.calle != calle : !calle.equals( _cast.calle )) {
			return false;
		}
		
		if (colonia == null ? _cast.colonia != colonia : !colonia.equals( _cast.colonia )) {
			return false;
		}
		
		if (codigoPostal != _cast.codigoPostal) {
			return false;
		}
		
		if (corredorIndustrial == null ? _cast.corredorIndustrial != corredorIndustrial : !corredorIndustrial.equals( _cast.corredorIndustrial )) {
			return false;
		}
		
		if (razonSocial == null ? _cast.razonSocial != razonSocial : !razonSocial.equals( _cast.razonSocial )) {
			return false;
		}
		
		if (filtro == null ? _cast.filtro != filtro : !filtro.equals( _cast.filtro )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (idConsulta ^ (idConsulta >>> 32));
		if (fecha != null) {
			_hashCode = 29 * _hashCode + fecha.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (int) (totalRegistros ^ (totalRegistros >>> 32));
		if (ubicacionGeografica != null) {
			_hashCode = 29 * _hashCode + ubicacionGeografica.hashCode();
		}
		
		if (actividadEconomica != null) {
			_hashCode = 29 * _hashCode + actividadEconomica.hashCode();
		}
		
		if (estratoPersonal != null) {
			_hashCode = 29 * _hashCode + estratoPersonal.hashCode();
		}
		
		if (nombreEstablecimiento != null) {
			_hashCode = 29 * _hashCode + nombreEstablecimiento.hashCode();
		}
		
		if (calle != null) {
			_hashCode = 29 * _hashCode + calle.hashCode();
		}
		
		if (colonia != null) {
			_hashCode = 29 * _hashCode + colonia.hashCode();
		}

                if (codigoPostal != null) {
			_hashCode = 29 * _hashCode + codigoPostal.hashCode();
		}
                
		//_hashCode = 29 * _hashCode + (int) (codigoPostal ^ (codigoPostal >>> 32));
		//_hashCode = 29 * _hashCode + (codigoPostalNull ? 1 : 0);

		if (corredorIndustrial != null) {
			_hashCode = 29 * _hashCode + corredorIndustrial.hashCode();
		}
		
		if (razonSocial != null) {
			_hashCode = 29 * _hashCode + razonSocial.hashCode();
		}
		
		if (filtro != null) {
			_hashCode = 29 * _hashCode + filtro.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ParamConsultaPk
	 */
	public ParamConsultaPk createPk()
	{
		return new ParamConsultaPk(idConsulta);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "tablealias.dto.dto.ParamConsulta: " );
		ret.append( "idConsulta=" + idConsulta );
		ret.append( ", fecha=" + fecha );
		ret.append( ", totalRegistros=" + totalRegistros );
		ret.append( ", ubicacionGeografica=" + ubicacionGeografica );
		ret.append( ", actividadEconomica=" + actividadEconomica );
		ret.append( ", estratoPersonal=" + estratoPersonal );
		ret.append( ", nombreEstablecimiento=" + nombreEstablecimiento );
		ret.append( ", calle=" + calle );
		ret.append( ", colonia=" + colonia );
		ret.append( ", codigoPostal=" + codigoPostal );
		ret.append( ", corredorIndustrial=" + corredorIndustrial );
		ret.append( ", razonSocial=" + razonSocial );
		ret.append( ", filtro=" + filtro );
		return ret.toString();
	}

    /**
     * @return the actividadEspecifica
     */
    public String getActividadEspecifica() {
        return actividadEspecifica;
    }

    /**
     * @param actividadEspecifica the actividadEspecifica to set
     */
    public void setActividadEspecifica(String actividadEspecifica) {
        this.actividadEspecifica = actividadEspecifica;
    }

}
