/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package tablealias.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the PARAM_CONSULTA table.
 */
public class ParamConsultaPk implements Serializable
{
	protected long idConsulta;

	/** 
	 * This attribute represents whether the primitive attribute idConsulta is null.
	 */
	protected boolean idConsultaNull;

	/** 
	 * Sets the value of idConsulta
	 */
	public void setIdConsulta(long idConsulta)
	{
		this.idConsulta = idConsulta;
	}

	/** 
	 * Gets the value of idConsulta
	 */
	public long getIdConsulta()
	{
		return idConsulta;
	}

	/**
	 * Method 'ParamConsultaPk'
	 * 
	 */
	public ParamConsultaPk()
	{
	}

	/**
	 * Method 'ParamConsultaPk'
	 * 
	 * @param idConsulta
	 */
	public ParamConsultaPk(final long idConsulta)
	{
		this.idConsulta = idConsulta;
	}

	/** 
	 * Sets the value of idConsultaNull
	 */
	public void setIdConsultaNull(boolean idConsultaNull)
	{
		this.idConsultaNull = idConsultaNull;
	}

	/** 
	 * Gets the value of idConsultaNull
	 */
	public boolean isIdConsultaNull()
	{
		return idConsultaNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ParamConsultaPk)) {
			return false;
		}
		
		final ParamConsultaPk _cast = (ParamConsultaPk) _other;
		if (idConsulta != _cast.idConsulta) {
			return false;
		}
		
		if (idConsultaNull != _cast.idConsultaNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) (idConsulta ^ (idConsulta >>> 32));
		_hashCode = 29 * _hashCode + (idConsultaNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "tablealias.dto.dto.ParamConsultaPk: " );
		ret.append( "idConsulta=" + idConsulta );
		return ret.toString();
	}

}
